### ISSUE TITLE
Issue with PlanarLazyGrid and SquareGrid

### ISSUE THREAD

**Issue by tylerscottr** [BorisTheBrave/sylves#3]
I found a bug in PlanarLazyMeshGrid.cs lines 105-106.

**Current Code:**
```
var strideX = ToVector2(chunkGrid.GetCellCenter(new Cell(1, 0)));
var strideY = ToVector2(chunkGrid.GetCellCenter(new Cell(0, 1)));
```

**Proposed Fix:**
```
var center0 = ToVector2(chunkGrid.GetCellCenter(new Cell(0, 0)));
var strideX = ToVector2(chunkGrid.GetCellCenter(new Cell(1, 0))) - center0;
var strideY = ToVector2(chunkGrid.GetCellCenter(new Cell(0, 1))) - center0;
```

What I've found is that the stride calculated for `SquareGrid`s is incorrect. The code would work correctly for `HexGrid`s because the origin cell for `HexGrid` is at `(0, 0, 0)`, but that is not true for `SquareGrid`s. Because of this bug, other functions such as `FindCell` do not work correctly.

By the way, so far I'm really liking this library. Keep up the good work!

**Comment by tylerscottr** [comment]
It occurs to me that I maybe don't understand how cell coordinates work. As such, I'm no longer convinced that there is a bug. Sorry! I'll get back to you if I come across actual issues.

**Comment by BorisTheBrave** [comment]
No, I think you are right the first time. I'll apply a fix.
